language: python
python:
    - 3.7
install:
  - pip install codecov
  - pip install pytest-cov
  - pip install -r requirements.txt
script:
  - pytest tests --cov=basic_validator
after_success:
  - codecov